name: stirling-pdf
services:
  web:
    image: stirling-pdf:local
    ports:
      - 8092:8080
    env:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=fr_FR
    volumes:
      - stirling-pdf-tessdata:/usr/share/tessdata
      - stirling-pdf-configs:/configs
      - stirling-pdf-logs:/logs
    network: stirling-pdf-net
    aliases:
      - web
    restart: always
    healthcheck: CMD-SHELL pgrep -f java || exit 0
networks:
  - stirling-pdf-net
