name: vaultwarden
services:
  web:
    image: vaultwarden:local
    ports:
      - 8082:80
    env:
      - DOMAIN=https://vaultwarden.example.com
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=change-this-admin-token
    volumes:
      - vaultwarden-data:/data
    network: vaultwarden-net
    aliases:
      - web
    restart: always
    healthcheck: CMD-SHELL pgrep -f vaultwarden || exit 0
networks:
  - vaultwarden-net
