name: nginx-proxy-manager
services:
  web:
    image: nginx-proxy-manager:local
    ports:
      - 8084:80
      - 8443:443
      - 8181:81
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    network: npm-net
    aliases:
      - web
    restart: always
    healthcheck: CMD-SHELL pgrep -f nginx || pgrep -f php-fpm || exit 0
networks:
  - npm-net
