name: vikunja
services:
  web:
    image: vikunja:local
    ports:
      - 3456:3456
    env:
      - VIKUNJA_DATABASE_HOST=db
      - VIKUNJA_DATABASE_PASSWORD=vikunja-pass
      - VIKUNJA_DATABASE_TYPE=mysql
      - VIKUNJA_DATABASE_USER=vikunja
      - VIKUNJA_DATABASE_DATABASE=vikunja
      - VIKUNJA_SERVICE_SECRET=changeme-secret-key-32-chars-long-secret
      - VIKUNJA_SERVICE_FRONTENDURL=http://localhost:3456
      - VIKUNJA_SERVICE_PUBLICURL=http://localhost:3456
    volumes:
      - vikunja-files:/app/vikunja/files
    network: vikunja-net
    aliases:
      - web
    depends_on:
      - db
    restart: always
    healthcheck: CMD-SHELL pgrep -f vikunja || exit 0
  db:
    image: mariadb:local
    env:
      - MYSQL_ROOT_PASSWORD=change-root
      - MYSQL_USER=vikunja
      - MYSQL_PASSWORD=vikunja-pass
      - MYSQL_DATABASE=vikunja
    volumes:
      - vikunja-db:/var/lib/mysql
      - vikunja-db-run:/run/mysqld
    network: vikunja-net
    aliases:
      - db
    restart: always
    healthcheck: CMD-SHELL mariadb-admin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" || exit 0
networks:
  - vikunja-net
