name: discourse

services:
  web:
    image: discourse:local
    ports:
      - 4000:80
    env:
      - DISCOURSE_DB_HOST=db
      - DISCOURSE_DB_PORT=5432
      - DISCOURSE_DB_USERNAME=discourse
      - DISCOURSE_DB_PASSWORD=discourse-pass
      - DISCOURSE_DB_NAME=discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT=6379
      - DISCOURSE_DEVELOPER_EMAILS=admin@example.com
      - DISCOURSE_HOSTNAME=localhost
      - DISCOURSE_SMTP_HOST=localhost
      - DISCOURSE_SMTP_PORT=587
    network: discourse-net
    aliases:
      - web
    depends_on:
      - db
      - redis
    restart: always
    healthcheck: CMD-SHELL pgrep -f ruby || pgrep -f puma || pgrep -f unicorn || pgrep -f nginx || exit 0

  db:
    image: postgres:local
    env:
      - POSTGRES_USER=discourse
      - POSTGRES_PASSWORD=discourse-pass
      - POSTGRES_DB=discourse
    volumes:
      - discourse-db:/var/lib/postgresql
      - discourse-db-run:/var/run/postgresql
    network: discourse-net
    aliases:
      - db
    restart: always
    healthcheck: CMD-SHELL pg_isready -U discourse -d discourse || exit 0

  redis:
    image: redis:local
    volumes:
      - discourse-redis:/data
    network: discourse-net
    aliases:
      - redis
    restart: always
    healthcheck: CMD-SHELL redis-cli ping || exit 0

networks:
  - discourse-net
