name: immich
services:
  web:
    image: immich:local
    ports:
      - 2283:2283
    env:
      - DB_HOSTNAME=db
      - DB_USERNAME=immich
      - DB_PASSWORD=immich-pass
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
      - NODE_ENV=production
    volumes:
      - immich-upload:/usr/src/app/upload
    network: immich-net
    aliases:
      - web
    depends_on:
      - db
      - redis
    restart: always
    healthcheck: CMD-SHELL pgrep -f node || exit 0
  microservices:
    image: immich:local
    env:
      - DB_HOSTNAME=db
      - DB_USERNAME=immich
      - DB_PASSWORD=immich-pass
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
      - NODE_ENV=production
    volumes:
      - immich-upload:/usr/src/app/upload
    network: immich-net
    aliases:
      - microservices
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: postgres:local
    env:
      - POSTGRES_USER=immich
      - POSTGRES_PASSWORD=immich-pass
      - POSTGRES_DB=immich
    volumes:
      - immich-db:/var/lib/postgresql/data
    network: immich-net
    aliases:
      - db
    restart: always
    healthcheck: CMD-SHELL pg_isready -U immich || exit 0
  redis:
    image: redis:local
    volumes:
      - immich-redis:/data
    network: immich-net
    aliases:
      - redis
    restart: always
    healthcheck: CMD-SHELL redis-cli ping || exit 0
networks:
  - immich-net
