name: libretranslate
services:
  web:
    image: libretranslate:local
    ports:
      - 5000:5000
    volumes:
      - libretranslate-data:/home/libretranslate/.local
    network: libretranslate-net
    aliases:
      - web
    restart: always
    healthcheck: CMD-SHELL pgrep -f python || pgrep -f gunicorn || exit 0
networks:
  - libretranslate-net
