name: bookstack
services:
  web:
    image: bookstack:local
    ports:
      - 8087:80
    env:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=http://127.0.0.1:8087
      - APP_KEY=base64:6R+jX3rj7w4ubR7sc92JouQBvzGJKWfVRO0XJkB4TgM=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bookstack
      - DB_USER=bookstack
      - DB_PASS=change-me
      - DB_USERNAME=bookstack
      - DB_PASSWORD=change-me
    volumes:
      - bookstack-data:/config
    network: bookstack-net
    aliases:
      - web
    depends_on:
      - db
    restart: always
    healthcheck: CMD-SHELL curl -f http://127.0.0.1/ || exit 1
  db:
    image: mariadb:local
    env:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=change-me
      - MYSQL_ROOT_PASSWORD=change-root
    volumes:
      - bookstack-db:/var/lib/mysql
    network: bookstack-net
    aliases:
      - db
    restart: always
    healthcheck: CMD-SHELL mariadb-admin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" || mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD"
networks:
  - bookstack-net
