name: uptime-kuma
services:
  web:
    image: uptime-kuma:local
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma-data:/app/data
    network: uptime-kuma-net
    aliases:
      - web
    restart: always
    healthcheck: CMD-SHELL pgrep -f node || exit 0
networks:
  - uptime-kuma-net
