name: static-site
services:
  web:
    image: caddy:local
    ports:
      - 8088:80
    volumes:
      - ./public:/usr/share/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
    network: static-site-net
    aliases:
      - web
    restart: always
    healthcheck: CMD-SHELL pgrep -f caddy || exit 0
networks:
  - static-site-net
