name: drawio
services:
  web:
    image: drawio:local
    ports:
      - 8089:8080
    network: drawio-net
    aliases:
      - web
    restart: always
    healthcheck: CMD-SHELL pgrep -f java || pgrep -f tomcat || exit 0
networks:
  - drawio-net
