name: syncthing
services:
  web:
    image: syncthing:local
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027
    volumes:
      - syncthing-config:/var/syncthing/config
      - ./sync:/var/syncthing/Sync
    network: syncthing-net
    aliases:
      - web
    restart: always
    healthcheck: CMD-SHELL wget -qO- http://127.0.0.1:8384/ || exit 1
networks:
  - syncthing-net
